Feature/#13/bot add twitter bot function
ryutah/lgbot pull request #14
Opened 2018-01-21 12:36 UTC by kazuki-m

ローカル環境でとりあえず動くようになったため、進捗報告も兼ねてpushします。
（GCP上の挙動は確認出来てません。）

ReceivePubSubMessage.java : ParDoの処理特に見て欲しいです。

2018-01-22 09:19 UTC, ryutah requested changes
Twitterの認証情報は要修正ですね。
あと、twitter4jの取得をGradle使う方法に変更も必要です。多分、ビルドツールとか使って依存解決できるようにしておかないとDataflowでアプリ実行するときにめんどくさいことになりそうなので。

他の指摘はまあ参考程度に。

2018-01-22 09:19 UTC, ryutah commented on bot/twitter/src/main/java/ReceivePubSubMessage.java
> +			c.output(url.toUpperCase());
なんでURLをupcaseしてるんですか？

2018-01-22 09:19 UTC, ryutah commented on bot/twitter/src/main/java/ReceivePubSubMessage.java
> +				// output
サブスクリプション名はコマンドライン引数を使って指定したほうがいいと思います。
[ココらへん](https://cloud.google.com/dataflow/pipelines/specifying-exec-params?hl=ja)が参考になるかと。

2018-01-22 09:19 UTC, ryutah commented on bot/twitter/src/main/java/twitter4j.properties
> +oauth.accessTokenSecret=Uy8fh8D1kjPrOJCzMUzrHlV1333Z5FCwfhfqgddjNZeBY
このGitHubプロジェクトはオープンなので、アクセストークンなどの認証情報はコードに含めないようにしてください。
これ晒しちゃうと、 最悪 **アカウントの乗っ取り** などをされる可能性もあります。

こういう外部に晒してはいけないような情報は、サブスクリプション名と同じように `コマンドライン引数` で実行時に指定するようにする、 `環境変数` から取得するようにする、 `設定ファイル自体を暗号化して、他人から推測されないようにする` などが考えられます。

とりあえず、今回は `コマンドライン引数` として指定する方法が妥当かな？という感じがします。

2018-01-22 09:19 UTC, ryutah commented on bot/twitter/src/main/java/TwitterBot.java
> +/**
Twitter APIのjarファイルをダウンロードして、手動でビルド設定に追加したかんじですかね？
そのやり方だと、他の人がこのコードPullしてきたときに依存関係が解決されず、ビルドエラーになります（実際、原の環境だとこのクラスはコンパイルエラーになってます）

このプロジェクトだと、 `Gradle` というビルドツールを使用しているので、それを使用してライブラリを追加するように変更してみてください。

`Gradle ライブラリ 追加` とか、 `twitter4j gradle` とかでググればやり方乗ってると思います。

2018-01-22 09:19 UTC, ryutah commented on bot/twitter/src/main/java/TwitterBot.java
> +
今時日本語が文字化けするようなサーバ使うような器械も減ってると思うんで、原的には別になんでもいいんですけど、ログに日本語とかのマルチバイト文字使うの嫌う人もいるんで、一応頭に覚えておいた方がいいかもです。

2018-01-22 09:19 UTC, ryutah commented on bot/twitter/src/main/java/ErrorConstants.java
> +
やりたいことは分かるんですが、ここまでする必要はないと思います。
TwitterAPIのエラーコードに変更などがあるたびにこのクラスの定義を変更しないといけなくなりますし、基本的にやっていることは通常のエラーメッセージの日本語訳だと思うので、改めて定義する意味も薄いです。

こういったことをやる場合は、エラーコードすべてを対応するのではなく、アプリケーションで気を使う必要があるエラーコードのみ定義するようにし、エラーメッセージなどはもとのエラーメッセージを置き換えるようにするのでなく、内容をわかりやすくするように付加情報を付与した形のメッセージに変形するような手法のほうが一般的だと思います。（ `some error occor` -> `user name : hoge, post message : fugafuga; some erorr occur` みたいに、メッセージをラップして原因の特定をしやすくするとか）

また、上記のような対応を取る場合もここでやっているように `エラーコード` : `何か` のようなハッシュマップで定義するのではなく、自作のエラークラスを作成するほうがオブジェクト指向的なコードになりますし、可読性も良くなりますね。

2018-01-22 09:19 UTC, ryutah commented on bot/twitter/src/main/java/OutputTwitterException.java
> +	private static final Logger LOGGER = Logger.getAnonymousLogger();
エラーをどのように扱うかにもよりますが、コードをリファクタリングをしたらこのクラスはおそらく不要になりますね。

2018-01-22 09:19 UTC, ryutah commented on bot/twitter/src/main/java/ReceivePubSubMessage.java
> +				TwitterBot twitterBot = new TwitterBot();
`old` みたいな識別子として使用するような文字列などはEnumを使うか定数可したほうがいいですね。
個人的にはEnumを使うほうが好きです。

2018-01-24 02:04 UTC, yoshioH commented on bot/twitter/src/main/java/ErrorConstants.java
> +
エラークラスについてのそもそも論についてはryutahが指摘してくれているので、それ以外のトピックスを追記していきます。

2018-01-24 03:00 UTC, yoshioH reviewed
総論についてはryutahが指摘している通りなので、細かいJavaの記法を中心にレビューしました。

2018-01-24 03:00 UTC, yoshioH commented on bot/twitter/src/main/java/ErrorConstants.java
> +	public static final Map<Integer, String> ExceptionContentsMaster;
定数（staticでfinalなやつ）はキャピタルなスネークケースで書くのが通例。

2018-01-24 03:00 UTC, yoshioH commented on bot/twitter/src/main/java/ErrorConstants.java
> +		ExceptionContentsMaster = Collections.unmodifiableMap(exception);
Map定数をCollections.unmodifiableMap使って書き換え不可にしているのはナイス。

2018-01-24 03:00 UTC, yoshioH commented on bot/twitter/src/main/java/ErrorConstants.java
> +		exception.put(89, "	Access Tokenが無効、もしくは期限切れです。");
このタブ文字には何か意味あるの？ログ出力の時にいい感じに文字がそろって見やすくなるとかする？

2018-01-24 03:00 UTC, yoshioH commented on bot/twitter/src/main/java/ErrorConstants.java
> +
補足。アプリケーションで使わないその他の例外の定義もしておかないともしもの時に困るよ。
それと、自作エラークラス内部でエラーハンドリング書くのが面倒だからオブジェクト内に隠蔽されたMapでお手軽ディスパッチするのはそれはそれでアリな手法だから、混乱しないようにねー。

2018-01-24 03:00 UTC, yoshioH commented on bot/twitter/src/main/java/ErrorConstants.java
> +	public static final Map<Integer, String> ExceptionContentsMaster;
`String errorMessage = ErrorConstants.ExceptionContentsMaster.get(errorCode);`
って定数にアクセスした後にMapのgetメソッドを使うことになるけど、クラスの外側にMapなんて意識させないほうがいいよ。
`ErrorDefinations.getMessageByErrorCode(errorCode);`
のようにメソッドを切って、Map操作をクラスの内側に隠蔽してあげるとGood。

2018-01-24 03:00 UTC, yoshioH commented on bot/twitter/src/main/java/OutputTwitterException.java
> +	public void ouputLog(TwitterException e) {
このメソッド、メンバ変数を使っているわけでもないし、わざわざインスタンスをnewして使うものなの？

2018-01-24 03:00 UTC, yoshioH commented on bot/twitter/src/main/java/OutputTwitterException.java
> +	private String ErrorMessage;
メンバ変数をコンストラクタやファクトリやDIなどによる初期化を心がけましょう。Setter依存はあまりよろしくない。

2018-01-24 03:02 UTC, yoshioH commented on bot/twitter/src/main/java/ErrorConstants.java
> +
自作エラークラス内部でエラーハンドリング書くのが面倒だからオブジェクト内に隠蔽されたMapでお手軽ディスパッチするのはそれはそれでアリな手法だから、混乱しないようにねー。

2018-01-24 03:24 UTC, yoshioH requested changes

2018-01-24 03:24 UTC, yoshioH commented on bot/twitter/src/main/java/ReceivePubSubMessage.java
> +		public void process(ProcessContext c) {
サイトのURLを取得する、サイトの判定結果を取得する、レガシーサイトだった場合にtweetする。
っていう３つのロジックを、それぞれをメソッドに分割すると可読性が上がってさらにいいよ。

2018-01-24 03:24 UTC, yoshioH commented on bot/twitter/src/main/java/ReceivePubSubMessage.java
> +			// レガシーサイトのURLを取得する
この時点でレガシーかどうかはまだ判定されていないよね？
コメントがウソにならないように気を付けて！

2018-01-24 03:42 UTC, ryutah commented on bot/twitter/src/main/java/ReceivePubSubMessage.java
> +		public void process(ProcessContext c) {
Apache Beam的には、トランスフォーム、フィルター、Twitter投稿のPCollectionをそれぞれ定義してあげるのがスタンダードなやり方だと思います。

```
Read Pub/Sub Message // Pipeline I/O
↓
Transform to Object has member of "URL" and "Label" // Transform
↓
Filter objects only labeled as "old" // Filter
↓
Post message to twitter // Pipeline I/O
```

みたいなフローですね。
それぞれDoFnをextendsしたクラスを定義して、パイプラインでつなげていきます。

メイン処理はこんな感じになるかと。

```java
public static void main(String[] args) {
    Pipeline p = Pipeline.create();

    p.apply(PubsubIO.readMessagesWithAttributes().fromSubscription("{SUBSCRIPTION_NAME}"))
     .apply("Convert to Some Object", ParDo.of(new ConvertDoFn()))
     .apply("Filtering only old site", ParDo.of(new FilterDoFn())
     .apply("Post message to twitter", ParDo.of(new TwitterPostDoFn())

    p.run();
}
```

2018-01-24 05:04 UTC, yoshioH commented on bot/twitter/src/main/java/ReceivePubSubMessage.java
> +		public void process(ProcessContext c) {
そういえば、Python版のパイプラインの繋げ方が気持ちイイって話もしたね。
確かに下手にメソッド分割せず、ApacheBeamに準拠した定義をしてあげるのが常道だ。フォローありがとう！

2018-02-03 09:47 UTC, ryutah commented
@kazuki-m リポジトリを分割したんで、そっちで改めてプルリク出してください。
このプルリクはCloseしちゃいます。

https://github.com/ryutah/lgbot-twitterbot

2018-02-03 09:47 UTC, closed without merging

2018-02-03 10:19 UTC, ryutah commented
やっぱこっちでオナシャス

https://github.com/dev-legbot/lgbot-twitterbot